<?php include('./header.php')?>
<div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;">
    <div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;">
        <div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;">
            <div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;">
                <div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;">
                    <div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;">
                        <div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;">
                            <div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;">
                                <h1 style="color: rgb(51, 51, 51);font-size: 20px;">CH&Iacute;NH S&Aacute;CH BẢO H&Agrave;NH</h1>
                            </div>
                            <div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;">
                                <h2 style="text-align: center;color: rgb(51, 51, 51);font-size: 20px;"><span style="font-size: 20px;"><span style="color: rgb(192, 57, 43);font-size: 20px;"><strong><strong style="font-size: 20px;"><span style="color: rgb(255, 255, 255);background-color: rgb(255, 255, 255);font-size: 20px;">QUY ĐỊNH VỀ CH&Iacute;NH S&Aacute;CH BẢO H&Agrave;NH</span></strong></strong></span></span></h2>
                                <h2 style="color: rgb(51, 51, 51);font-size: 20px;"><span style="font-size: 18px;"><strong><strong style="font-size: 18px;"><span style="color: rgb(231, 76, 60);font-size: 18px;">&gt;&gt;&gt; Tra cứu bảo h&agrave;nh</span> <a href="https://tinhocngoisao.com/pages/tra-cuu-bao-hanh" style="color: transparent;font-size: 18px;"><span style="color: rgb(41, 128, 185);font-size: 18px;">tại đ&acirc;y</span></a></strong></strong></span></h2>
                                <h2 style="color: rgb(51, 51, 51);font-size: 20px;"><span style="font-size: 18px;"><strong><strong style="font-size: 18px;">I. ĐỊA ĐIỂM BẢO H&Agrave;NH:</strong></strong></span></h2>
                                <h3 style="color: rgb(51, 51, 51);font-size: 18px;"><span style="font-size: 15px;"><strong><strong style="font-size: 15px;"><span style="color: rgb(230, 126, 34);font-size: 15px;">1. NHẬN BẢO H&Agrave;NH</span></strong></strong></span></h3>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">Tất cả h&agrave;ng h&oacute;a Tin Học Ng&ocirc;i Sao b&aacute;n ra đều được bảo h&agrave;nh tại :</span></p>
                                <p style="font-size: 14px;">✦<span style="font-size: 15px;">&nbsp;<strong><strong style="font-size: 15px;">Trung t&acirc;m bảo h&agrave;nh</strong></strong>: Lầu 1 - Số&nbsp;28-30 Trần Triệu Luật, P.6, Q.T&acirc;n B&igrave;nh, TP.HCM</span></p>
                                <p style="font-size: 14px;">✦ <span style="font-size: 15px;"><strong><strong style="font-size: 15px;">Hotline nhận h&agrave;ng (kh&aacute;ch đến trực tiếp trung t&acirc;m bảo h&agrave;nh Tin Học&nbsp;Ng&ocirc;i Sao)</strong></strong> : 0919 267 015.<br><strong><strong style="font-size: 15px;">Quy tr&igrave;nh:</strong></strong> Nh&acirc;n vi&ecirc;n giao dịch bảo h&agrave;nh nhận, ra bi&ecirc;n nhận ngay, sau đ&oacute; c&oacute; tin nhắn mời kh&aacute;ch h&agrave;ng mang bi&ecirc;n nhận đến nhận h&agrave;ng.</span></p>
                                <p style="font-size: 14px;">✦<span style="font-size: 15px;">&nbsp;<strong><strong style="font-size: 15px;">Hotline nhận h&agrave;ng (kh&aacute;ch h&agrave;ng gởi bảo h&agrave;nh qua xe/chuyển ph&aacute;t)</strong></strong> : 0903 955 507 (Trung t&acirc;m Bảo h&agrave;nh Tin Học Ng&ocirc;i Sao)<br><strong><strong style="font-size: 15px;">Quy tr&igrave;nh:&nbsp;</strong></strong>nhận h&agrave;ng, khi h&agrave;ng về, đ&oacute;ng h&agrave;ng v&agrave; vận&nbsp;chuyển tận nh&agrave;.</span></p>
                                <p style="font-size: 14px;">✦<span style="font-size: 15px;"><strong><strong style="font-size: 15px;">&nbsp;Tiếp nhận phản &aacute;nh:</strong></strong><br>- Email: phananhbaohanh@tinhocngoisao.com<br>- Hotline: 0931 889 888 - CSKH</span></p>
                                <p style="font-size: 14px;">✦ <span style="font-size: 15px;"><strong><strong style="font-size: 15px;">Giờ l&agrave;m việc</strong></strong>:<br>Từ Thứ 2 đến Thứ 7 (giờ h&agrave;nh ch&iacute;nh)<br>- S&aacute;ng 08h30 - 12h00<br>- Chiều 13h00 - 17h30<br>Nghỉ trưa 60 ph&uacute;t (từ 12h00 - 13h00)</span></p>
                                <p style="font-size: 14px;">✦ <span style="font-size: 15px;"><strong><strong style="font-size: 15px;">Thời gian lấy&nbsp;số thứ tự bảo h&agrave;nh</strong></strong> : S&aacute;ng 08h30 - 12h00 ; Chiều 13h00 - 17h30.</span></p>
                                <h3 style="color: rgb(51, 51, 51);font-size: 18px;"><span style="font-size: 15px;"><span style="color: rgb(230, 126, 34);font-size: 15px;"><strong><strong style="font-size: 15px;">2. TRẢ BẢO H&Agrave;NH</strong></strong></span></span></h3>
                                <p style="font-size: 14px;">✦ <span style="font-size: 15px;">&nbsp;<strong><strong style="font-size: 15px;">Địa chỉ trả h&agrave;ng bảo h&agrave;nh</strong></strong>: 28-30 Trần Triệu Luật, P.6, Q.T&acirc;n B&igrave;nh, TP.HCM</span></p>
                                <h2 style="color: rgb(51, 51, 51);font-size: 20px;"><span style="font-size: 18px;"><strong><strong style="font-size: 18px;">II. ĐIỀU KIỆN BẢO H&Agrave;NH</strong></strong></span></h2>
                                <p style="font-size: 14px;"><span style="font-size: 15px;"><strong><strong style="font-size: 15px;">2.1&nbsp;</strong></strong>Sản phẩm đang trong thời hạn bảo h&agrave;nh, c&oacute; tem bảo h&agrave;nh của nh&agrave; ph&acirc;n phối v&agrave; c&oacute; tem Ng&ocirc;i Sao. Hư hỏng được x&aacute;c định do lỗi kỹ thuật hoặc do lỗi của nh&agrave; sản xuất.</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;"><strong><strong style="font-size: 15px;">2.2&nbsp;</strong></strong>Tem bảo h&agrave;nh v&agrave; m&atilde; vạch của c&ocirc;ng ty, của nh&agrave; cung cấp phải nguy&ecirc;n vẹn, kh&ocirc;ng r&aacute;ch rời, vỡ n&aacute;t&nbsp;, biến dạng ; kh&ocirc;ng bị tẩy xo&aacute;...</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;"><strong><strong style="font-size: 15px;">2.3&nbsp;</strong></strong>Sản phẩm phải c&ograve;n nguy&ecirc;n vẹn, kh&ocirc;ng cong, v&ecirc;nh, rạn nứt, trầy xước, sứt mẻ, nứt khe cắm, vỡ...</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;"><strong><strong style="font-size: 15px;">2.4&nbsp;</strong></strong>D&ugrave;ng đ&uacute;ng nguồn điện, kh&ocirc;ng bị mối mọt, c&ocirc;n tr&ugrave;ng x&acirc;m nhập; kh&ocirc;ng ch&aacute;y nổ, phồng tụ; kh&ocirc;ng bị &ocirc; xy ho&aacute; do đặt trong m&ocirc;i trường ẩm ướt...</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;"><strong><strong style="font-size: 15px;">2.5</strong></strong> Chưa can thiệp v&agrave;o phần cứng (tự &yacute; th&aacute;o dỡ, sửa chữa...).</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;"><strong><strong style="font-size: 15px;">2.6&nbsp;</strong></strong>C&aacute;c điều kiện bảo h&agrave;nh của Ng&ocirc;i Sao đều tu&acirc;n theo ti&ecirc;u chuẩn bảo h&agrave;nh của h&atilde;ng sản xuất hoặc nh&agrave; ph&acirc;n phối tại Việt Nam.<br><strong><strong style="font-size: 15px;">TH&Ocirc;NG TIN LI&Ecirc;N HỆ BẢO H&Agrave;NH THEO H&Atilde;NG</strong></strong></span></p>
                                <table cellspacing="0" style="color: transparent;font-size: 14px;border-collapse: collapse;">
                                    <tbody style="font-size: 14px;">
                                        <tr>
                                            <td style="text-align: center;color: black;font-size: 14px;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://www.dell.com/support/home/en-vn?app=warranty" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">DELL</span></span></a></span></span></span></span></span></strong></strong></td>
                                            <td style="text-align: center;font-size: 14px;border-left: none;border-right: 1px solid black;border-top: 1px solid black;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://amdvietnam.vn/chinh-sach-bao-hanh.html" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">AMD</span></span></a></span></span></span></span></span></strong></strong></td>
                                            <td style="text-align: center;font-size: 14px;border-left: none;border-right: 1px solid black;border-top: 1px solid black;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://www.lg.com/vn/tro-giup/bao-hanh" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">LG</span></span></a></span></span></span></span></span></strong></strong></td>
                                            <td style="text-align: center;font-size: 14px;border-left: none;border-right: 1px solid black;border-top: 1px solid black;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://www.asus.com/support/images/upload/ee6559a7-9868-4949-8411-06f022e5893e.pdf" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">ASUS</span></span></a></span></span></span></span></span></strong></strong></td>
                                            <td style="text-align: center;font-size: 14px;border-left: none;border-right: 1px solid black;border-top: 1px solid black;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://www.samsung.com/vn/support/warranty/" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">SAMSUNG</span></span></a></span></span></span></span></span></strong></strong></td>
                                        </tr>
                                        <tr>
                                            <td style="text-align: center;font-size: 14px;border-left: 1px solid black;border-right: 1px solid black;border-top: none;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://support.hp.com/vn-en" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">HP</span></span></a></span></span></span></span></span></strong></strong></td>
                                            <td style="text-align: center;font-size: 14px;border-left: none;border-right: 1px solid black;border-top: none;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://western.com.vn/media/news/2410_chinh-sach-bao-hanh-tai-trung-tam-wd-viet-nam-1.jpg" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">WESTERN</span></span></a></span></span></span></span></span></strong></strong></td>
                                            <td style="text-align: center;font-size: 14px;border-left: none;border-right: 1px solid black;border-top: none;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://www.logitech.com/vi-vn/tos/terms.html?id=3101.html" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">LOGITECH</span></span></a></span></span></span></span></span></strong></strong></td>
                                            <td style="text-align: center;font-size: 14px;border-left: none;border-right: 1px solid black;border-top: none;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://www.gigabyte.com/vn/Support/Warranty" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">GIGABYTE</span></span></a></span></span></span></span></span></strong></strong></td>
                                            <td style="text-align: center;font-size: 14px;border-left: none;border-right: 1px solid black;border-top: none;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://www.acer.com/vn-vi/support/warranty" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">ACER</span></span></a></span></span></span></span></span></strong></strong></td>
                                        </tr>
                                        <tr>
                                            <td style="text-align: center;font-size: 14px;border-left: 1px solid black;border-right: 1px solid black;border-top: none;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://www.toshiba-lifestyle.com/vn/dieu-khoan-bao-hanh" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">TOSHIBA</span></span></a></span></span></span></span></span></strong></strong></td>
                                            <td style="text-align: center;font-size: 14px;border-left: none;border-right: 1px solid black;border-top: none;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://vn.aoc.com/index/explore/route/warranty" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">AOC</span></span></a></span></span></span></span></span></strong></strong></td>
                                            <td style="text-align: center;font-size: 14px;border-left: none;border-right: 1px solid black;border-top: none;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://www.tp-link.com/vn/support/replacement-warranty/" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">TP - LINK</span></span></a></span></span></span></span></span></strong></strong></td>
                                            <td style="text-align: center;font-size: 14px;border-left: none;border-right: 1px solid black;border-top: none;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://www.seagate.com/as/en/support/vietnam/" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">SEAGATE</span></span></a></span></span></span></span></span></strong></strong></td>
                                            <td style="text-align: center;font-size: 14px;border-left: none;border-right: 1px solid black;border-top: none;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://support.lenovo.com/vn/en/warrantylookup#/" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">LENOVO</span></span></a></span></span></span></span></span></strong></strong></td>
                                        </tr>
                                        <tr>
                                            <td style="text-align: center;font-size: 14px;border-left: 1px solid black;border-right: 1px solid black;border-top: none;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://vn.msi.com/page/warranty" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">MSI</span></span></a></span></span></span></span></span></strong></strong></td>
                                            <td style="text-align: center;font-size: 14px;border-left: none;border-right: 1px solid black;border-top: none;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://www.intel.vn/content/www/vn/vi/support/articles/000005494/processors.html" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">INTEL</span></span></a></span></span></span></span></span></strong></strong></td>
                                            <td style="text-align: center;font-size: 14px;border-left: none;border-right: 1px solid black;border-top: none;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://www.viewsonic.com/vn/support/warranty/" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">VIEWSONIC</span></span></a></span></span></span></span></span></strong></strong></td>
                                            <td style="text-align: center;font-size: 14px;border-left: none;border-right: 1px solid black;border-top: none;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://www.zotac.com/vn/page/product-warranty-policy" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">ZOTAC</span></span></a></span></span></span></span></span></strong></strong></td>
                                            <td style="text-align: center;font-size: 14px;border-left: none;border-right: 1px solid black;border-top: none;border-bottom: 1px solid black;"><strong><strong style="font-size: 14px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><span style="font-size: 15px;"><a target="_blank" href="https://imouhome.vn/chinh-sach-bao-hanh-hau-mai-imou" rel="nofollow" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;"><span style="font-size: 15px;">IMOU</span></span></a></span></span></span></span></span></strong></strong></td>
                                        </tr>
                                    </tbody>
                                </table>
                                <p style="font-size: 14px;"><span style="font-size: 15px;"><strong><strong style="font-size: 15px;">2.7</strong></strong> Với mặt h&agrave;ng CPU tray socket 1155, 1150, 1151, AMD..., Ng&ocirc;i Sao ngo&agrave;i d&aacute;n tem c&ograve;n ghi serial tr&ecirc;n phiếu b&aacute;n h&agrave;ng. Qu&yacute; kh&aacute;ch h&agrave;ng nhớ kiểm tra serial khi mua h&agrave;ng để dễ d&agrave;ng bảo h&agrave;nh sau n&agrave;y . V&igrave; khi qu&yacute; kh&aacute;ch h&agrave;ng bảo h&agrave;nh CPU, nếu tr&ecirc;n phần mềm Ng&ocirc;i Sao kh&ocirc;ng c&oacute; serial, Ng&ocirc;i Sao c&oacute; quyền từ chối bảo h&agrave;nh, kể cả khi c&oacute; tem Ng&ocirc;i Sao ở CPU đ&oacute;.</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;"><strong><strong style="font-size: 15px;">2.8</strong></strong> Qu&yacute; kh&aacute;ch h&agrave;ng lưu trữ phiếu xuất kho b&aacute;n h&agrave;ng để tiện bảo h&agrave;nh, hoặc đổi trả trong 07 ng&agrave;y. Qu&yacute; kh&aacute;ch h&agrave;ng c&oacute; thể trưng bản chụp h&igrave;nh phiếu b&aacute;n h&agrave;ng, để tiện cho Ng&ocirc;i Sao tra cứu phần mềm.</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;"><strong><strong style="font-size: 15px;">2.9&nbsp;</strong></strong>Với&nbsp;h&agrave;ng cũ,&nbsp;khi đến bảo h&agrave;nh, qu&yacute; kh&aacute;ch h&agrave;ng n&ecirc;n mang&nbsp;đầy đủ phụ kiện&nbsp;giống l&uacute;c mua,&nbsp;để trong trương hợp hết h&agrave;ng đổi, Ng&ocirc;i Sao sẽ ho&agrave;n tiền lại qu&yacute; kh&aacute;ch. Tr&aacute;nh t&igrave;nh trạng phải trừ tiền phụ kiện. VD: kh&ocirc;ng c&oacute; chắn lưng main trừ 30.000 đ / c&aacute;i.</span></p>
                                <h2 style="color: rgb(51, 51, 51);font-size: 20px;"><span style="font-size: 18px;"><strong><strong style="font-size: 18px;">III. ĐIỀU KIỆN KH&Ocirc;NG BẢO H&Agrave;NH</strong></strong></span></h2>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">3.1 Sản phẩm hết thời hạn bảo h&agrave;nh. &nbsp;Thiết bị kh&ocirc;ng do Ng&ocirc;i Sao b&aacute;n ra.</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">3.2 Tem bảo h&agrave;nh, m&atilde; vạch, chỉ số dung lượng, số serial number bị r&aacute;ch, mờ c&oacute; dấu hiệu cạo sửa hay đ&aacute;nh tr&aacute;o.</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">3.3 Thiết bị do va chạm hoặc đ&atilde; bị rơi rớt, bể mẻ, m&oacute;p m&eacute;o, biến dạng, trầy xước, rỉ x&eacute;t, x&igrave; hoặc ph&ugrave; tụ &hellip;</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">3.4 Thiết bị c&oacute; dấu hiệu ch&aacute;y nổ, chuột bọ, c&ocirc;n tr&ugrave;ng x&acirc;m nhập hoặc đặt trong m&ocirc;i trường ẩm ướt.</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">3.5 Hư hỏng do thi&ecirc;n tai hoả hoạn, sử dụng nguồn điện kh&ocirc;ng ổn định hoặc do vận chuyển kh&ocirc;ng đ&uacute;ng quy c&aacute;ch.</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">3.6 Kh&ocirc;ng bảo h&agrave;nh c&aacute;c lỗi do phần mềm g&acirc;y ra, c&aacute;c phụ kiện ti&ecirc;u hao đi k&egrave;m như: quạt, mực, d&acirc;y c&aacute;p... ri&ecirc;ng apdater của c&aacute;c thiết bị Modem, Access Point, LCD... vẫn bảo h&agrave;nh 1 th&aacute;ng</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">3.7 Ng&ocirc;i Sao kh&ocirc;ng chịu tr&aacute;ch nhiệm với dữ liệu trong ổ cứng, SSD hư...</span></p>
                                <h2 style="color: rgb(51, 51, 51);font-size: 20px;"><span style="font-size: 18px;"><strong><strong style="font-size: 18px;">IV. THỜI GIAN GIỮ BẢO H&Agrave;NH</strong></strong></span></h2>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">4.1 &nbsp;Nếu h&agrave;ng thuộc diện bảo h&agrave;nh 1 đổi 1 của Ng&ocirc;i Sao : kh&aacute;ch HCM trong 02 giờ l&agrave;m việc trừ trường hợp hết h&agrave;ng ; kh&aacute;ch tỉnh trong 7 ng&agrave;y l&agrave;m việc ( kh&ocirc;ng t&iacute;nh chủ nhật ) t&iacute;nh từ l&uacute;c nhận h&agrave;ng tại c&ocirc;ng ty hoặc căn cứ theo ng&agrave;y Ng&ocirc;i Sao nhận h&agrave;ng c&ocirc;ng bố tr&ecirc;n Website.</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">4.2 Nếu phải mang đi bảo h&agrave;nh ch&iacute;nh h&atilde;ng : Trong v&ograve;ng 10 ng&agrave;y l&agrave;m việc ( kh&ocirc;ng t&iacute;nh thứ 7 v&agrave; chủ nhật ) t&iacute;nh từ l&uacute;c nhận h&agrave;ng.</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">4.3 &nbsp;Thời gian bảo h&agrave;nh c&oacute; thể sớm hơn hoặc chậm hơn t&ugrave;y trường hợp. Khi qu&aacute; thời hạn b&ecirc;n tr&ecirc;n, ch&uacute;ng t&ocirc;i sẽ th&ocirc;ng b&aacute;o l&yacute; do ch&iacute;nh đ&aacute;ng đến kh&aacute;ch h&agrave;ng. Thời gian tối đa cho một trường hợp &nbsp;bảo h&agrave;nh &nbsp;game l&agrave; 30 ng&agrave;y v&agrave; coin l&agrave; 45 ng&agrave;y. Với v&agrave;i trường hợp kh&ocirc;ng đủ điều kiện bảo h&agrave;nh, Ng&ocirc;i Sao nhận thấy c&oacute; thể h&atilde;ng hỗ trợ, Ng&ocirc;i Sao vẫn tạm nhận đi bảo h&agrave;nh h&atilde;ng, nhưng thời gian trả h&agrave;ng phụ thuộc v&agrave;o h&atilde;ng ( thường 2-6 th&aacute;ng v&igrave; đi nước ngo&agrave;i</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">4.4 &nbsp;Trường hợp h&agrave;ng bảo h&agrave;nh kh&ocirc;ng c&ograve;n h&agrave;ng đổi do đ&atilde; ngưng sản xuất hoặc kh&ocirc;ng c&ograve;n kinh doanh.Ch&uacute;ng t&ocirc;i sẽ xử l&yacute; như sau :</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">Kh&aacute;ch h&agrave;ng c&oacute; thể lựa chọn một trong c&aacute;c c&aacute;ch sau :</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">4.4.1. &nbsp;Đổi một sản phẩm tương đương (nếu c&oacute;) v&agrave; sản phẩm n&agrave;y kh&ocirc;ng nhất thiết phải l&agrave; h&agrave;ng mới 100%.</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">4.4.2. &nbsp;Đổi một sản phẩm cấp cao hơn nếu kh&aacute;ch h&agrave;ng đồng &yacute; mức gi&aacute; thương lượng đổi b&ugrave; *. Thời hạn bảo h&agrave;nh được đ&aacute;nh dấu tiếp tục t&iacute;nh theo thời hạn bảo h&agrave;nh của sản phẩm cũ.</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">4.4.3. &nbsp;Thương lượng ho&agrave;n tiền với việc khấu trừ cụ thể như sau</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;"><em style="font-size: 15px;"><strong><strong style="font-size: 15px;">H&agrave;ng mới:</strong></strong></em></span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">+ Với SP bh 36 th&aacute;ng : khấu trừ 05%/th&aacute;ng. T&iacute;nh từ th&aacute;ng thứ 1<br>+ Với SP bh 24 th&aacute;ng : Khấu trừ 10%/th&aacute;ng. T&iacute;nh từ th&aacute;ng thứ 1<br>+ Với SP bh 12 th&aacute;ng : Khấu trừ 10%/th&aacute;ng. T&iacute;nh từ th&aacute;ng thứ 1</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;"><strong><strong style="font-size: 15px;"><em style="font-size: 15px;">H&agrave;ng cũ&nbsp;- t&iacute;nh thời gian bảo h&agrave;nh theo tem NS :</em></strong></strong></span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">+ Với SP bh 12 th&aacute;ng : khấu trừ &nbsp;10%/th&aacute;ng thứ 1.<br>+ Với SP bh 06 th&aacute;ng : Khấu trừ 10%/th&aacute;ng. T&iacute;nh từ th&aacute;ng thứ 1<br>+ Với SP bh 03 th&aacute;ng : Khấu trừ 15%/th&aacute;ng thứ 1&nbsp;v&agrave; 10% th&aacute;ng thứ 2 trở đi.</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">Tối đa cho việc khấu trừ l&agrave; 70% gi&aacute; trị sản phẩm. Gi&aacute; trị khấu trừ được t&iacute;nh theo gi&aacute; thị trường tại thời điểm khấu trừ. Nếu h&agrave;ng h&oacute;a kh&ocirc;ng c&ograve;n sẽ căn cứ v&agrave;o gi&aacute; của sản phẩm c&oacute; hiệu năng tương tự sản phẩm khấu trừ.</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;"><span style="color: rgb(231, 76, 60);font-size: 15px;"><em style="font-size: 15px;"><strong><strong style="font-size: 15px;">Qu&yacute; kh&aacute;ch lưu &yacute;&nbsp;</strong></strong></em>:</span> Xin qu&yacute; kh&aacute;ch giữ bi&ecirc;n nhận bảo h&agrave;nh cẩn thận để mang bi&ecirc;n nhận đến nhận h&agrave;ng bảo h&agrave;nh xong. Nếu mất bi&ecirc;n nhận QU&Yacute; KH&Aacute;CH VUI L&Ograve;NG ĐỢI TRONG V&Ograve;NG 30 NG&Agrave;Y, SAU Đ&Oacute; CUNG CẤP GIẤY TỜ T&Ugrave;Y TH&Acirc;N, HOẶC GIẤY GIỚI THIỆU NẾU L&Agrave; C&Ocirc;NG TY (KH&Ocirc;NG GIẢI QUYẾT C&Aacute;C TRƯỜNG HỢP NGOẠI LỆ). NẾU QU&Aacute; 40 NG&Agrave;Y, NSL SẼ TỪ CHỐI XỬ L&Yacute;.</span></p>
                                <h2 style="color: rgb(51, 51, 51);font-size: 20px;"><span style="font-size: 18px;"><strong><strong style="font-size: 18px;">V. C&Aacute;C CHẾ ĐỘ BẢO H&Agrave;NH ĐẶC BIỆT</strong></strong></span></h2>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">5.1 Tất cả c&aacute;c sản phẩm b&aacute;n ra c&oacute; chế độ bảo h&agrave;nh 1 đổi 1 đều được Ng&ocirc;i Sao ghi tr&ecirc;n phiếu xuất kho b&aacute;n h&agrave;ng, v&agrave; đồng thời c&ocirc;ng bố tr&ecirc;n web TinHocNgoiSao.com.<br>Xem th&ecirc;m <strong><strong style="font-size: 15px;"><a href="https://tinhocngoisao.com/collections/bao-hanh-sieu-toc-48h/" style="color: transparent;font-size: 15px;"><span style="color: rgb(41, 128, 185);font-size: 15px;">ch&iacute;nh s&aacute;ch&nbsp;bảo h&agrave;nh si&ecirc;u tốc 1h tại đ&acirc;y</span></a></strong></strong>.</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">5.2 Tất cả sản phẩm cũ do Ng&ocirc;i Sao b&aacute;n ra đều c&oacute; chế độ bảo h&agrave;nh 1 đổi 1 trong v&ograve;ng 01 th&aacute;ng đầu.</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">5.3 Ng&ocirc;i sao c&oacute; chế độ bảo h&agrave;nh đặc biệt tốt với sản phẩm thương hiệu NetLike, Warship, Apoint, Wincom, Homesound....: 1 đổi 1 trong v&ograve;ng 1h ; 50% xuất h&agrave;ng đổi mới ; trong v&agrave;i trường hợp đặc biệt vẫn bảo h&agrave;nh d&ugrave; kh&ocirc;ng đủ điều kiện bảo h&agrave;nh (kh&ocirc;ng tem hoặc mất &frac12; tem m&agrave; chưa c&oacute; dấu hiệu sửa ; s&uacute;t d&acirc;y, sứt mẻ mức độ nhẹ&hellip; )</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">5.4 Ng&ocirc;i sao thực hiện ch&iacute;nh s&aacute;ch bảo h&agrave;nh v&agrave; đổi trả sản phẩm theo quy định của h&atilde;ng v&agrave; nh&agrave; ph&acirc;n phối.</span></p>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">5.5 SSD bảo h&agrave;nh theo 2 điều kiện l&agrave; 3 năm v&agrave; tổng dung lượng đọc ghi tối đa của ổ cứng (TBW) kh&ocirc;ng vượt qu&aacute; ni&ecirc;m yết của nh&agrave; sản xuất cho Model đ&oacute;.</span></p>
                                <h2 style="color: rgb(51, 51, 51);font-size: 20px;"><span style="font-size: 18px;"><strong><strong style="font-size: 18px;">VI. CHI PH&Iacute; VẬN CHUYỂN ĐỐI VỚI KH&Aacute;CH H&Agrave;NG TỈNH</strong></strong></span></h2>
                                <p style="font-size: 14px;"><span style="font-size: 15px;">Gi&aacute; b&aacute;n của ch&uacute;ng t&ocirc;i chưa bao gồm chi ph&iacute; vận chuyển. Nhưng với đầu về, Ng&ocirc;i Sao đ&oacute;ng trả h&agrave;ng rất cẩn thận v&agrave; giao tận nh&agrave; qu&yacute; kh&aacute;ch với mức ph&iacute; tiết kiệm (chỉ tương đương ch&agrave;nh xe ) để tr&aacute;nh mất m&aacute;t. Ngo&agrave;i ra, Ch&uacute;ng t&ocirc;i sẽ hỗ trợ nhận h&agrave;ng bảo h&agrave;nh tại ch&agrave;nh xe/ hoặc b&ecirc;n chuyển ph&aacute;t qu&yacute; kh&aacute;ch y&ecirc;u cầu. H&agrave;ng hằng ng&agrave;y nhận được, Ng&ocirc;i Sao đều cập nhật l&ecirc;n web để qu&yacute; kh&aacute;ch tham khảo h&agrave;ng ng&agrave;y.</span></p>
                            </div>
                        </div>
                    </div>
                    <div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;">
                        <div style="font-size: 14px;"><br></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;">
    <div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;">
        <div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;">
            <div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;">
                <div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;">
                    <div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;">
                        <div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;">
                            <div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;">
                                <h2 style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 20px;"><span style="font-size: 18px;"><strong><strong style="font-size: 18px;">VII. C&Aacute;CH THỨC TIN HỌC NG&Ocirc;I SAO NHẬN H&Agrave;NG ĐỔI TRẢ</strong></strong></span></h2>
                                <p style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;"><span style="font-size: 15px;"><strong><strong style="font-size: 15px;"><u>A. Khu vực HCM :</u></strong></strong> Qu&yacute; kh&aacute;ch mang trực tiếp sản phẩm cần đổi trả v&agrave;o Khu Bảo H&agrave;nh (quầy đổi trả h&agrave;ng) tại chi nh&aacute;nh T&acirc;n B&igrave;nh để được kiểm tra hỗ trợ. Nếu đủ điều kiện trả h&agrave;ng v&agrave; trong thời gian đổi trả cho ph&eacute;p, th&igrave; nh&acirc;n vi&ecirc;n sẽ l&agrave;m phiếu v&agrave; kh&aacute;ch h&agrave;ng nhận lại tiền mặt tại quầy Thu_Chi ở khu vực Giao Nhận (đối diện khu bảo h&agrave;nh) của C&ocirc;ng Ty</span></p>
                                <p style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;"><span style="font-size: 15px;"><strong><strong style="font-size: 15px;"><u>B. Khu vực tỉnh :</u></strong></strong>chuyển ph&aacute;t nhanh tới tận c&ocirc;ng ty Tin Học&nbsp;Ng&ocirc;i Sao.</span></p>
                                <p style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;"><span style="font-size: 15px;">1. H&agrave;ng h&oacute;a kh&aacute;ch h&agrave;ng đ&oacute;ng g&oacute;i cẩn thận tr&aacute;nh hư hỏng, va đập để tr&aacute;nh bị từ chối nhận lại.&nbsp;Ri&ecirc;ng với mặt h&agrave;ng điện tử dễ vỡ, xin qu&yacute; kh&aacute;ch kh&ocirc;ng gởi dịch vụ chuyển ph&aacute;t Viettel (l&yacute; do: Ng&ocirc;i Sao đ&atilde; gởi qua dịch vụ n&agrave;y ra miền bắc v&agrave; m&agrave;n h&igrave;nh bị vỡ tỷ lệ tr&ecirc;n 40%)</span></p>
                                <p style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;"><span style="font-size: 15px;">2. Vui l&ograve;ng ghi Th&ocirc;ng tin người nhận :</span></p>
                                <p style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;"><span style="font-size: 15px;">- <strong><strong style="font-size: 15px;">PH&Ograve;NG BẢO H&Agrave;NH C&Ocirc;NG TY TIN HỌC NG&Ocirc;I SAO</strong></strong></span></p>
                                <p style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;"><span style="font-size: 15px;">(Vui l&ograve;ng kh&ocirc;ng ghi t&ecirc;n người nhận l&agrave; nh&acirc;n vi&ecirc;n Kinh Doanh)</span></p>
                                <p style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;"><span style="font-size: 15px;">- Địa chỉ : 28-30 Trần Triệu Luật, P.6, Q.T&acirc;n B&igrave;nh, TP.HCM</span></p>
                                <p style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;"><span style="font-size: 15px;">- SĐT: <strong><strong style="font-size: 15px;"><u>0903 955 507</u></strong></strong></span></p>
                                <p style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;"><span style="font-size: 15px;">1. Phải ghi họ t&ecirc;n - địa chỉ người gởi cực r&otilde; v&agrave; số điện thoại li&ecirc;n lạc được. V&igrave; h&agrave;ng bảo h&agrave;nh xong, Ng&ocirc;i Sao trả tận nh&agrave; n&ecirc;n cần th&ocirc;ng tin ch&iacute;nh x&aacute;c 100%.</span></p>
                                <p style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;"><span style="font-size: 15px;">1. Trong v&ograve;ng 01 ng&agrave;y,&nbsp;h&agrave;ng mỗi ng&agrave;y nhận được, Ng&ocirc;i Sao đều cập nhật để qu&yacute; kh&aacute;ch y&ecirc;n t&acirc;m.</span></p>
                                <p style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;"><span style="font-size: 15px;">2. Sau khi nhận h&agrave;ng, ch&uacute;ng t&ocirc;i sẽ tiến h&agrave;nh kiểm tra xem sản phẩm c&oacute; đủ điều kiện để đổi h&agrave;ng - trả h&agrave;ng hay kh&ocirc;ng. V&agrave; th&ocirc;ng b&aacute;o đến kh&aacute;ch h&agrave;ng cụ thể.</span></p>
                                <p style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;"><span style="font-size: 15px;">3. Thời gian mở kiện h&agrave;ng v&agrave; l&agrave;m bi&ecirc;n nhận &nbsp;: tối đa kh&ocirc;ng qu&aacute; 02 ng&agrave;y l&agrave;m việc để từ l&uacute;c nhận h&agrave;ng. Thời gian Ng&ocirc;i Sao ra nhận h&agrave;ng nh&agrave; xe : tối đa 02 ng&agrave;y l&agrave;m việc kể từ khi nghe nh&agrave; xe hoặc kh&aacute;ch h&agrave;ng th&ocirc;ng b&aacute;o.</span></p>
                                <p style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;"><span style="font-size: 15px;">4. Ph&iacute; gởi h&agrave;ng :&nbsp;Ng&ocirc;i Sao đ&oacute;ng trả h&agrave;ng rất cẩn thận v&agrave;&nbsp;giao tận nh&agrave;&nbsp;qu&yacute; kh&aacute;ch với mức ph&iacute; tiết kiệm (chỉ tương đương ch&agrave;nh xe) để tr&aacute;nh hư hỏng linh kiện cho qu&yacute; kh&aacute;ch.</span></p>
                                <p style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;"><span style="font-size: 15px;">5. Mọi thắc mắc, khiếu nại về th&aacute;i độ phục vụ của nh&acirc;n vi&ecirc;n. Qu&yacute; kh&aacute;ch vui l&ograve;ng li&ecirc;n hệ:<br>- SDT : <span style="color: rgb(231, 76, 60);font-size: 15px;"><strong><strong style="font-size: 15px;"><em style="font-size: 15px;">0931 889 888 - CSKH</em></strong></strong></span><br>- Email : <a href="email%3Acskh@tinhocngoisao.com" style="color: transparent;font-size: 15px;"><span style="color: rgb(231, 76, 60);font-size: 15px;">cskh@tinhocngoisao.com</span></a></span></p>
                                <p style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;"><span style="font-size: 15px;">Qu&yacute; kh&aacute;ch c&oacute; thể gửi phản ảnh v&agrave;o Email để Tin Học Ng&ocirc;i Sao phục vụ qu&yacute; kh&aacute;ch tốt hơn.</span></p>
                                <p style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;"><span style="font-size: 15px;">Ch&acirc;n th&agrave;nh c&aacute;m ơn qu&yacute; kh&aacute;ch đ&atilde; tin tưởng v&agrave; ủng hộ Tin Học Ng&ocirc;i Sao - Rất h&acirc;n hạnh v&agrave; sẵn s&agrave;ng phục vụ qu&yacute; kh&aacute;ch.</span></p>
                            </div>
                        </div>
                    </div>
                    <div style="text-align: start;color: rgb(51, 51, 51);background-color: rgb(255, 255, 255);font-size: 14px;"><br></div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php include('./footer.php')?>